/**
 * Copyrigt (2019, ) Institute of Software, Chinese Academy of Sciences
 */
package com.github.kubesys.webfrk;

import java.util.Base64;

/**
 * @author wuheng@otcaix.iscas.ac.cn
 * @author chace
 * @since 2019.10.29
 *
 */

public class TokenTest  {

	public static void main(String[] args) {
		String token = "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqSnFiVzlxZEd4amR6a3lVbXBEVVd4R2JrSlhkVkpmVUZZMGMwTnVZelZwT0c5U04xUmxhM0UyZVhjaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbUZrYldsdUxYUnZhMlZ1TFhScVptZzFJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1Ym1GdFpTSTZJbUZrYldsdUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaU1UTmtZalkzTjJFdFlUZGtNUzAwTTJGbUxUazBOMll0TXpsbE5UQXpZekZqTXpRNElpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbVJsWm1GMWJIUTZZV1J0YVc0aWZRLmswM0pwOU53QzlhMnVpVE52elE1UVRXOEM3SkQzSVk2U0xSZ2NyZUlzZXBxckVxMXFYby03cmcwSDVTYTk4ekwyOWlReUlpQWdiZzg1YXA1aTYzVEtfX2Y2X0laX0dadjR2aVNNb2ZRczR5aV8yUEFTc3p2R3VaT3Rlem5qVXh2UGkwUnRpclFjZmZlZHhCWWR2T1FFX1VKU0hjNUd5OVR6V0xFdFRUTnNrSEtxd2l6Y05qRlpOMWJzNzkzQzRJcGYwR2EzdXgzQUU5Rkl1cUdWTWVCaDIzb2Y5bkx6T3JKVDdsTHRBdXNpNGNCZGh6STR2MzNhVndYNVFuVXRCT2ZSY2NXQTNDQU9XTjJFekpBMGhJSlJaRXp1bTZpS09UdEoxMDZJZXFsSFdnRmRiVWxuMlNUZ0MwSEhiYlpMOFJqVVB0LVlzUVlucnVnTUlnZzlOMFdsQQ==";
		System.out.println(new String(Base64.getDecoder().decode(token)));
	}
	
}
